version: '3.8'

services:
  http:
    build:
      context: . 
    volumes:
      - ./http:/app/http
    image: sherifwaelnagaty/flask-app-dockerization  
    environment:
      FLASK_APP: http/app.py  # Adjust the path to where your Flask app entry point is
      FLASK_ENV: development
    command: flask run --host=0.0.0.0 --port=5000
    restart: always
    networks:
      - webnet

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always  
    depends_on:
      - http
    networks:
      - webnet

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: root
    volumes:
      - ./backup.sh:/backup.sh
      - mysql_data:/var/lib/mysql
    restart: always    
    depends_on:
      - http
    networks:
      - webnet

volumes:
  mysql_data:

networks:
  webnet:
