
services:
  http:
    build:
      context: . 
    ports:
      - "5000:5000"  # Map port 5000 of the host to port 5000 of the container
    volumes:
      - ./http:/app/http
    environment:
      FLASK_APP: http/app.py  # Adjust the path to where your Flask app entry point is
      FLASK_ENV: development
    command: flask run --host=0.0.0.0 --port=5000
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always  
    depends_on:
      - http
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: root
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always    
    depends_on:
      - http
volumes:
  mysql_data:           